# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: workspace).
# Unity Catalog includes only ISOLATED securables bound exclusively to this workspace.
# Review before importing.

# Catalogs to manage. Key = catalog name; value = catalog settings.
# A catalog must be declared here before its schemas or grants can be added.
catalogs = {
  sales = {
    comment        = "Sales domain"
    isolation_mode = "ISOLATED"
    owner          = "data-platform"
    properties = {
      team = "sales"
    }
    storage_root = "abfss://sales@lake.dfs.core.windows.net/"
  }
}
