# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: workspace).
# Unity Catalog includes only ISOLATED securables bound exclusively to this workspace.
# Review before importing.

# Cluster policies. Key = policy name; value = policy settings.
# Set exactly one of definition or policy_family_id. Permissions are nested inline.
cluster_policies = {
  "Job Family Policy" = {
    libraries = []
    permissions = [{
      permission_level       = "CAN_USE"
      service_principal_name = "etl-sp"
    }]
    policy_family_definition_overrides = {
      "custom_tags.team" = {
        type  = "fixed"
        value = "data"
      }
    }
    policy_family_id = "job-cluster"
  }
  "Team Policy" = {
    definition = {
      autotermination_minutes = {
        defaultValue = 30
        maxValue     = 60
        type         = "range"
      }
      spark_version = {
        type  = "fixed"
        value = "15.4.x-scala2.12"
      }
    }
    description = "Pinned runtime for team clusters"
    libraries = [{
      pypi = {
        package = "great-expectations==0.18.0"
      }
    }]
    max_clusters_per_user = 2
    permissions = [{
      group_name       = "data-engineers"
      permission_level = "CAN_USE"
    }]
  }
}
