# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: workspace).
# Unity Catalog includes only ISOLATED securables bound exclusively to this workspace.
# Review before importing.

# External locations. Key = location name; value = settings including url and credential_name.
# credential_name can reference a credential managed here or an existing shared credential.
external_locations = {
  lake_raw = {
    comment            = "Raw zone"
    credential_name    = "lake_cred"
    enable_file_events = true
    fallback           = false
    isolation_mode     = "ISOLATION_MODE_ISOLATED"
    owner              = "data-platform"
    read_only          = false
    url                = "abfss://raw@lake.dfs.core.windows.net/"
  }
}
