# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: workspace).
# Review before importing.

# Account-level service principals managed by another Terraform root.
# Key = readable alias; value = Databricks application ID.
external_service_principals = {}
