# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: workspace).
# Unity Catalog includes only ISOLATED securables bound exclusively to this workspace.
# Review before importing.

# Direct grants ON an external location. Shape: location name -> principal -> [privileges].
external_location_access = {
  lake_raw = {
    data-engineers = ["READ_FILES", "WRITE_FILES"]
  }
}
