# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: workspace).
# Unity Catalog includes only ISOLATED securables bound exclusively to this workspace.
# Review before importing.

# Instance pools. Key = pool name; value = pool settings.
# Permissions are nested inline under each pool's permissions list.
instance_pools = {
  shared-pool = {
    azure_attributes = {
      availability       = "ON_DEMAND_AZURE"
      spot_bid_max_price = -1
    }
    custom_tags = {
      cost_center = "1234"
    }
    enable_elastic_disk                   = true
    idle_instance_autotermination_minutes = 15
    max_capacity                          = 10
    min_idle_instances                    = 1
    node_type_id                          = "Standard_DS3_v2"
    permissions = [{
      permission_level = "CAN_MANAGE"
      user_name        = "jon@example.com"
    }]
    preloaded_spark_versions = ["15.4.x-scala2.12"]
  }
}
