# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: workspace).
# Unity Catalog includes only ISOLATED securables bound exclusively to this workspace.
# Review before importing.

# Schemas to manage. Key = catalog name; value = list of schema names in that catalog.
# The catalog key must also exist in the catalogs block. Empty list = catalog managed, no schemas.
schemas = {
  sales = ["bronze", "silver"]
}
