# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: workspace).
# Unity Catalog includes only ISOLATED securables bound exclusively to this workspace.
# Review before importing.

# Optional custom managed storage location per schema.
# Shape: catalog -> schema -> abfss URL. Only for schemas that do not use the catalog default.
schema_storage_roots = {
  sales = {
    bronze = "abfss://sales@lake.dfs.core.windows.net/bronze"
  }
}
