# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: workspace).
# Unity Catalog includes only ISOLATED securables bound exclusively to this workspace.
# Review before importing.

# Optional schema descriptions. Shape: catalog -> schema -> comment string.
schema_comments = {
  sales = {
    bronze = "Raw landing"
  }
}
