# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: workspace).
# Unity Catalog includes only ISOLATED securables bound exclusively to this workspace.
# Review before importing.

# Direct grants ON a schema. Shape: catalog -> schema -> principal -> [privileges].
# Only needed for grants beyond what the schema already inherits from catalog_access.
schema_access = {
  sales = {
    bronze = {
      "ingest@example.com" = ["MODIFY", "SELECT"]
    }
    silver = {}
  }
}
