# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: workspace).
# Unity Catalog includes only ISOLATED securables bound exclusively to this workspace.
# Review before importing.

# Secret scopes (prefer Key Vault-backed). Key = scope name; value = settings.
# ACLs are nested inline under acls: principal -> permission. Do not put secret values here.
secret_scopes = {
  db-scope = {
    acls = {
      "jon@example.com" = "MANAGE"
    }
  }
  kv-scope = {
    acls = {
      admins         = "MANAGE"
      data-engineers = "READ"
    }
    keyvault_metadata = {
      dns_name    = "https://kv-data.vault.azure.net/"
      resource_id = "/subscriptions/sub/resourceGroups/rg/providers/Microsoft.KeyVault/vaults/kv-data"
    }
  }
}
