# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: workspace).
# Unity Catalog includes only ISOLATED securables bound exclusively to this workspace.
# Review before importing.

# Service principals. Key = readable alias; value = display name and entitlements.
# Leave application_id unset for a new Databricks-managed one; Databricks generates it.
service_principals = {
  dup-sp-1 = {
    allow_cluster_create       = false
    allow_instance_pool_create = false
    databricks_sql_access      = false
    display_name               = "dup-sp"
    workspace_access           = false
  }
  dup-sp-2 = {
    allow_cluster_create       = true
    allow_instance_pool_create = false
    databricks_sql_access      = false
    display_name               = "dup-sp"
    workspace_access           = false
    workspace_consume          = true
  }
  etl-sp = {
    allow_cluster_create       = false
    allow_instance_pool_create = false
    databricks_sql_access      = true
    workspace_access           = true
  }
}
