# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: workspace).
# Unity Catalog includes only ISOLATED securables bound exclusively to this workspace.
# Review before importing.

# Service principals. Key = display name; value = entitlements.
# Leave application_id unset for a new Databricks-managed one; Databricks generates it.
service_principals = {
  "dup-sp (a1b2c3d4-0000-0000-0000-000000000002)" = {
    allow_cluster_create       = false
    allow_instance_pool_create = false
    databricks_sql_access      = false
    display_name               = "dup-sp"
    workspace_access           = false
  }
  "dup-sp (a1b2c3d4-0000-0000-0000-000000000003)" = {
    allow_cluster_create       = true
    allow_instance_pool_create = false
    databricks_sql_access      = false
    display_name               = "dup-sp"
    workspace_access           = false
    workspace_consume          = true
  }
  etl-sp = {
    allow_cluster_create       = false
    allow_instance_pool_create = false
    databricks_sql_access      = true
    workspace_access           = true
  }
}
