# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: workspace).
# Unity Catalog includes only ISOLATED securables bound exclusively to this workspace.
# Review before importing.

# Direct grants ON a storage credential. Shape: credential name -> principal -> [privileges].
storage_credential_access = {
  lake_cred = {
    data-platform-admins = ["ALL_PRIVILEGES"]
  }
}
