# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: workspace).
# Unity Catalog includes only ISOLATED securables bound exclusively to this workspace.
# Review before importing.

# Unity Catalog storage credentials. Key = credential name; value = settings
# (for Azure, an azure_managed_identity referencing an existing access connector).
storage_credentials = {
  lake_cred = {
    azure_managed_identity = {
      access_connector_id = "/subscriptions/sub/resourceGroups/rg/providers/Microsoft.Databricks/accessConnectors/lake-ac"
      managed_identity_id = "/subscriptions/sub/resourceGroups/rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/lake-mi"
    }
    comment        = "Lake access connector"
    isolation_mode = "ISOLATION_MODE_ISOLATED"
    owner          = "data-platform"
    read_only      = false
  }
}
