# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: workspace).
# Unity Catalog includes only ISOLATED securables bound exclusively to this workspace.
# Review before importing.

# Catalogs to manage. Key = catalog name; value = catalog settings.
# A catalog must be declared here before its schemas or grants can be added.
catalogs = {
  sales = {
    comment        = "Sales domain"
    isolation_mode = "ISOLATED"
    owner          = "data-platform"
    properties = {
      team = "sales"
    }
    storage_root = "abfss://sales@lake.dfs.core.windows.net/"
  }
}

# Direct grants ON a catalog. Shape: catalog name -> principal -> [privileges].
# Principals: groups/users by name or email; service principals by application id.
# Grants here are inherited by the catalog's schemas; do not repeat them in schema_access.
catalog_access = {
  sales = {
    a1b2c3d4-0000-0000-0000-000000000001 = ["SELECT", "USE_CATALOG", "USE_SCHEMA"]
    data-engineers                       = ["CREATE_SCHEMA", "USE_CATALOG", "USE_SCHEMA"]
  }
}

# Schemas to manage. Key = catalog name; value = list of schema names in that catalog.
# The catalog key must also exist in the catalogs block. Empty list = catalog managed, no schemas.
schemas = {
  sales = ["bronze", "silver"]
}

# Direct grants ON a schema. Shape: catalog -> schema -> principal -> [privileges].
# Only needed for grants beyond what the schema already inherits from catalog_access.
schema_access = {
  sales = {
    bronze = {
      "ingest@example.com" = ["MODIFY", "SELECT"]
    }
    silver = {}
  }
}

# Optional custom managed storage location per schema.
# Shape: catalog -> schema -> abfss URL. Only for schemas that do not use the catalog default.
schema_storage_roots = {
  sales = {
    bronze = "abfss://sales@lake.dfs.core.windows.net/bronze"
  }
}

# Optional schema descriptions. Shape: catalog -> schema -> comment string.
schema_comments = {
  sales = {
    bronze = "Raw landing"
  }
}

# Unity Catalog storage credentials. Key = credential name; value = settings
# (for Azure, an azure_managed_identity referencing an existing access connector).
storage_credentials = {
  lake_cred = {
    azure_managed_identity = {
      access_connector_id = "/subscriptions/sub/resourceGroups/rg/providers/Microsoft.Databricks/accessConnectors/lake-ac"
      managed_identity_id = "/subscriptions/sub/resourceGroups/rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/lake-mi"
    }
    comment        = "Lake access connector"
    isolation_mode = "ISOLATION_MODE_ISOLATED"
    owner          = "data-platform"
    read_only      = false
  }
}

# Direct grants ON a storage credential. Shape: credential name -> principal -> [privileges].
storage_credential_access = {
  lake_cred = {
    data-platform-admins = ["ALL_PRIVILEGES"]
  }
}

# External locations. Key = location name; value = settings including url and credential_name.
# credential_name can reference a credential managed here or an existing shared credential.
external_locations = {
  lake_raw = {
    comment            = "Raw zone"
    credential_name    = "lake_cred"
    enable_file_events = true
    fallback           = false
    isolation_mode     = "ISOLATION_MODE_ISOLATED"
    owner              = "data-platform"
    read_only          = false
    url                = "abfss://raw@lake.dfs.core.windows.net/"
  }
}

# Direct grants ON an external location. Shape: location name -> principal -> [privileges].
external_location_access = {
  lake_raw = {
    data-engineers = ["READ_FILES", "WRITE_FILES"]
  }
}

# Unity Catalog workspace bindings. Key = provider import ID.
# Shape: <workspace_id>|<securable_type>|<securable_name> -> binding settings.
workspace_bindings = {
  "1111|catalog|sales" = {
    binding_type   = "BINDING_TYPE_READ_WRITE"
    securable_name = "sales"
    securable_type = "catalog"
    workspace_id   = 1111
  }
  "1111|external_location|lake_raw" = {
    binding_type   = "BINDING_TYPE_READ_WRITE"
    securable_name = "lake_raw"
    securable_type = "external_location"
    workspace_id   = 1111
  }
  "1111|storage_credential|lake_cred" = {
    binding_type   = "BINDING_TYPE_READ_WRITE"
    securable_name = "lake_cred"
    securable_type = "storage_credential"
    workspace_id   = 1111
  }
}

# Cluster policies. Key = policy name; value = policy settings.
# Set exactly one of definition or policy_family_id. Permissions are nested inline.
cluster_policies = {
  "Job Family Policy" = {
    libraries = []
    permissions = [{
      permission_level       = "CAN_USE"
      service_principal_name = "a1b2c3d4-0000-0000-0000-000000000001"
    }]
    policy_family_definition_overrides = {
      "custom_tags.team" = {
        type  = "fixed"
        value = "data"
      }
    }
    policy_family_id = "job-cluster"
  }
  "Team Policy" = {
    definition = {
      autotermination_minutes = {
        defaultValue = 30
        maxValue     = 60
        type         = "range"
      }
      spark_version = {
        type  = "fixed"
        value = "15.4.x-scala2.12"
      }
    }
    description = "Pinned runtime for team clusters"
    libraries = [{
      pypi = {
        package = "great-expectations==0.18.0"
      }
    }]
    max_clusters_per_user = 2
    permissions = [{
      group_name       = "data-engineers"
      permission_level = "CAN_USE"
    }]
  }
}

# Instance pools. Key = pool name; value = pool settings.
# Permissions are nested inline under each pool's permissions list.
instance_pools = {
  shared-pool = {
    azure_attributes = {
      availability       = "ON_DEMAND_AZURE"
      spot_bid_max_price = -1
    }
    custom_tags = {
      cost_center = "1234"
    }
    enable_elastic_disk                   = true
    idle_instance_autotermination_minutes = 15
    max_capacity                          = 10
    min_idle_instances                    = 1
    node_type_id                          = "Standard_DS3_v2"
    permissions                           = []
    preloaded_spark_versions              = ["15.4.x-scala2.12"]
  }
}

# SQL warehouses. Key = warehouse name; value = warehouse settings.
# Permissions are nested inline under each warehouse's permissions list.
warehouses = {
  "Analytics WH" = {
    auto_stop_mins            = 20
    cluster_size              = "Small"
    enable_photon             = true
    enable_serverless_compute = true
    max_num_clusters          = 3
    min_num_clusters          = 1
    permissions = [{
      group_name       = "analysts"
      permission_level = "CAN_USE"
    }]
    spot_instance_policy = "COST_OPTIMIZED"
    tags = {
      team = "analytics"
    }
    warehouse_type = "PRO"
  }
}

# Secret scopes (prefer Key Vault-backed). Key = scope name; value = settings.
# ACLs are nested inline under acls: principal -> permission. Do not put secret values here.
secret_scopes = {
  db-scope = {
    acls = {
      "jon@example.com" = "MANAGE"
    }
  }
  kv-scope = {
    acls = {
      admins         = "MANAGE"
      data-engineers = "READ"
    }
    keyvault_metadata = {
      dns_name    = "https://kv-data.vault.azure.net/"
      resource_id = "/subscriptions/sub/resourceGroups/rg/providers/Microsoft.KeyVault/vaults/kv-data"
    }
  }
}

# Service principals. Key = display name; value = entitlements.
# Leave application_id unset for a new Databricks-managed one; Databricks generates it.
service_principals = {
  "dup-sp (a1b2c3d4-0000-0000-0000-000000000002)" = {
    allow_cluster_create       = false
    allow_instance_pool_create = false
    databricks_sql_access      = false
    display_name               = "dup-sp"
    workspace_access           = false
  }
  "dup-sp (a1b2c3d4-0000-0000-0000-000000000003)" = {
    allow_cluster_create       = true
    allow_instance_pool_create = false
    databricks_sql_access      = false
    display_name               = "dup-sp"
    workspace_access           = false
    workspace_consume          = true
  }
  etl-sp = {
    allow_cluster_create       = false
    allow_instance_pool_create = false
    databricks_sql_access      = true
    workspace_access           = true
  }
}
