# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: workspace).
# Unity Catalog includes only ISOLATED securables bound exclusively to this workspace.
# Review before importing.

# SQL warehouses. Key = warehouse name; value = warehouse settings.
# Permissions are nested inline under each warehouse's permissions list.
warehouses = {
  "Analytics WH" = {
    auto_stop_mins            = 20
    cluster_size              = "Small"
    enable_photon             = true
    enable_serverless_compute = true
    max_num_clusters          = 3
    min_num_clusters          = 1
    permissions = [{
      group_name       = "analysts"
      permission_level = "CAN_USE"
    }]
    spot_instance_policy = "COST_OPTIMIZED"
    tags = {
      team = "analytics"
    }
    warehouse_type = "PRO"
  }
}
