# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: workspace).
# Unity Catalog includes only ISOLATED securables bound exclusively to this workspace.
# Review before importing.

# Unity Catalog workspace bindings. Key = provider import ID.
# Shape: <workspace_id>|<securable_type>|<securable_name> -> binding settings.
workspace_bindings = {
  "1111|catalog|sales" = {
    binding_type   = "BINDING_TYPE_READ_WRITE"
    securable_name = "sales"
    securable_type = "catalog"
    workspace_id   = 1111
  }
  "1111|external_location|lake_raw" = {
    binding_type   = "BINDING_TYPE_READ_WRITE"
    securable_name = "lake_raw"
    securable_type = "external_location"
    workspace_id   = 1111
  }
  "1111|storage_credential|lake_cred" = {
    binding_type   = "BINDING_TYPE_READ_WRITE"
    securable_name = "lake_cred"
    securable_type = "storage_credential"
    workspace_id   = 1111
  }
}
