# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: workspace).
# Unity Catalog includes only ISOLATED securables bound exclusively to this workspace.
# Review before importing.

# Account identities assigned to this workspace. Key = Databricks principal ID.
# Service principal entitlements use the same workspace-level provider.
workspace_permission_assignments = {
  "100" = {
    permissions            = ["USER"]
    principal_id           = 100
    service_principal_name = "a1b2c3d4-0000-0000-0000-000000000001"
    service_principal_entitlements = {
      allow_cluster_create       = false
      allow_instance_pool_create = false
      databricks_sql_access      = true
      workspace_access           = true
      workspace_consume          = false
    }
  }
  "200" = {
    permissions  = ["ADMIN"]
    principal_id = 200
    user_name    = "jon@example.com"
  }
  "300" = {
    permissions  = ["USER"]
    principal_id = 300
    group_name   = "data-engineers"
  }
}
