# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: shared).
# Unity Catalog includes OPEN securables and ISOLATED securables bound to zero or many workspaces.
# Review before importing.

# Catalogs to manage. Key = catalog name; value = catalog settings.
# A catalog must be declared here before its schemas or grants can be added.
catalogs = {
  shared_ref = {
    comment        = "Reference data shared by every workspace"
    isolation_mode = "OPEN"
    owner          = "data-platform"
  }
}
