# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: shared).
# Unity Catalog includes OPEN securables and ISOLATED securables bound to zero or many workspaces.
# Review before importing.

# Direct grants ON a catalog. Shape: catalog name -> principal -> [privileges].
# Principals: groups/users by name or email; service principals by application id.
# Grants here are inherited by the catalog's schemas; do not repeat them in schema_access.
catalog_access = {
  shared_ref = {
    "account users" = ["SELECT", "USE_CATALOG", "USE_SCHEMA"]
  }
}
