# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: shared).
# Unity Catalog includes OPEN securables and ISOLATED securables bound to zero or many workspaces.
# Review before importing.

# External locations. Key = location name; value = settings including url and credential_name.
# credential_name can reference a credential managed here or an existing shared credential.
external_locations = {
  public_ref = {
    credential_name    = "shared_cred"
    enable_file_events = false
    fallback           = false
    isolation_mode     = "ISOLATION_MODE_OPEN"
    owner              = "data-platform"
    read_only          = true
    url                = "abfss://ref@lake.dfs.core.windows.net/"
  }
}
