# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: shared).
# Unity Catalog includes OPEN securables and ISOLATED securables bound to zero or many workspaces.
# Review before importing.

# Direct grants ON an external location. Shape: location name -> principal -> [privileges].
external_location_access = {
  public_ref = {}
}
