# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: shared).
# Unity Catalog includes OPEN securables and ISOLATED securables bound to zero or many workspaces.
# Review before importing.

# Schemas to manage. Key = catalog name; value = list of schema names in that catalog.
# The catalog key must also exist in the catalogs block. Empty list = catalog managed, no schemas.
schemas = {
  shared_ref = ["ref"]
}
