# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: shared).
# Unity Catalog includes OPEN securables and ISOLATED securables bound to zero or many workspaces.
# Review before importing.

# Optional schema descriptions. Shape: catalog -> schema -> comment string.
schema_comments = {
  shared_ref = {
    ref = "Lookup tables"
  }
}
