# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: shared).
# Unity Catalog includes OPEN securables and ISOLATED securables bound to zero or many workspaces.
# Review before importing.

# Direct grants ON a schema. Shape: catalog -> schema -> principal -> [privileges].
# Only needed for grants beyond what the schema already inherits from catalog_access.
schema_access = {
  shared_ref = {
    ref = {}
  }
}
