# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: shared).
# Unity Catalog includes OPEN securables and ISOLATED securables bound to zero or many workspaces.
# Review before importing.

# Optional custom managed storage location per schema.
# Shape: catalog -> schema -> abfss URL. Only for schemas that do not use the catalog default.
schema_storage_roots = {}
