# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: shared).
# Unity Catalog includes OPEN securables and ISOLATED securables bound to zero or many workspaces.
# Review before importing.

# Direct grants ON a storage credential. Shape: credential name -> principal -> [privileges].
storage_credential_access = {
  shared_cred = {
    data-engineers = ["CREATE_EXTERNAL_LOCATION"]
  }
}
