# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: shared).
# Unity Catalog includes OPEN securables and ISOLATED securables bound to zero or many workspaces.
# Review before importing.

# Unity Catalog storage credentials. Key = credential name; value = settings
# (for Azure, an azure_managed_identity referencing an existing access connector).
storage_credentials = {
  shared_cred = {
    azure_managed_identity = {
      access_connector_id = "/subscriptions/sub/resourceGroups/rg/providers/Microsoft.Databricks/accessConnectors/shared-ac"
    }
    isolation_mode = "ISOLATION_MODE_ISOLATED"
    owner          = "data-platform"
    read_only      = true
  }
}
