# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: shared).
# Unity Catalog includes OPEN securables and ISOLATED securables bound to zero or many workspaces.
# Review before importing.

# Catalogs to manage. Key = catalog name; value = catalog settings.
# A catalog must be declared here before its schemas or grants can be added.
catalogs = {
  shared_ref = {
    comment        = "Reference data shared by every workspace"
    isolation_mode = "OPEN"
    owner          = "data-platform"
  }
}

# Direct grants ON a catalog. Shape: catalog name -> principal -> [privileges].
# Principals: groups/users by name or email; service principals by application id.
# Grants here are inherited by the catalog's schemas; do not repeat them in schema_access.
catalog_access = {
  shared_ref = {
    "account users" = ["SELECT", "USE_CATALOG", "USE_SCHEMA"]
  }
}

# Schemas to manage. Key = catalog name; value = list of schema names in that catalog.
# The catalog key must also exist in the catalogs block. Empty list = catalog managed, no schemas.
schemas = {
  shared_ref = ["ref"]
}

# Direct grants ON a schema. Shape: catalog -> schema -> principal -> [privileges].
# Only needed for grants beyond what the schema already inherits from catalog_access.
schema_access = {
  shared_ref = {
    ref = {}
  }
}

# Optional custom managed storage location per schema.
# Shape: catalog -> schema -> abfss URL. Only for schemas that do not use the catalog default.
schema_storage_roots = {}

# Optional schema descriptions. Shape: catalog -> schema -> comment string.
schema_comments = {
  shared_ref = {
    ref = "Lookup tables"
  }
}

# Unity Catalog storage credentials. Key = credential name; value = settings
# (for Azure, an azure_managed_identity referencing an existing access connector).
storage_credentials = {
  shared_cred = {
    azure_managed_identity = {
      access_connector_id = "/subscriptions/sub/resourceGroups/rg/providers/Microsoft.Databricks/accessConnectors/shared-ac"
    }
    isolation_mode = "ISOLATION_MODE_ISOLATED"
    owner          = "data-platform"
    read_only      = true
  }
}

# Direct grants ON a storage credential. Shape: credential name -> principal -> [privileges].
storage_credential_access = {
  shared_cred = {
    data-engineers = ["CREATE_EXTERNAL_LOCATION"]
  }
}

# External locations. Key = location name; value = settings including url and credential_name.
# credential_name can reference a credential managed here or an existing shared credential.
external_locations = {
  public_ref = {
    credential_name    = "shared_cred"
    enable_file_events = false
    fallback           = false
    isolation_mode     = "ISOLATION_MODE_OPEN"
    owner              = "data-platform"
    read_only          = true
    url                = "abfss://ref@lake.dfs.core.windows.net/"
  }
}

# Direct grants ON an external location. Shape: location name -> principal -> [privileges].
external_location_access = {
  public_ref = {}
}

# Unity Catalog workspace bindings. Key = provider import ID.
# Shape: <workspace_id>|<securable_type>|<securable_name> -> binding settings.
workspace_bindings = {
  "1111|storage_credential|shared_cred" = {
    binding_type   = "BINDING_TYPE_READ_WRITE"
    securable_name = "shared_cred"
    securable_type = "storage_credential"
    workspace_id   = 1111
  }
  "2222|storage_credential|shared_cred" = {
    binding_type   = "BINDING_TYPE_READ_WRITE"
    securable_name = "shared_cred"
    securable_type = "storage_credential"
    workspace_id   = 2222
  }
}
