# GENERATED by datatf from https://adb-1111.1.azuredatabricks.net (scope: shared).
# Unity Catalog includes OPEN securables and ISOLATED securables bound to zero or many workspaces.
# Review before importing.

# Unity Catalog workspace bindings. Key = provider import ID.
# Shape: <workspace_id>|<securable_type>|<securable_name> -> binding settings.
workspace_bindings = {
  "1111|storage_credential|shared_cred" = {
    binding_type   = "BINDING_TYPE_READ_WRITE"
    securable_name = "shared_cred"
    securable_type = "storage_credential"
    workspace_id   = 1111
  }
  "2222|storage_credential|shared_cred" = {
    binding_type   = "BINDING_TYPE_READ_WRITE"
    securable_name = "shared_cred"
    securable_type = "storage_credential"
    workspace_id   = 2222
  }
}
